# Generated by Django 3.1.6 on 2021-02-15 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('additional_answer_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalStep',
            fields=[
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.step')),
                ('is_go', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FirstStep',
            fields=[
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.step')),
            ],
        ),
        migrations.CreateModel(
            name='InterstitialStep',
            fields=[
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.step')),
            ],
        ),
        migrations.CreateModel(
            name='NextStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.choice')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.step')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.step'),
        ),
    ]
