# Generated by Django 3.1.6 on 2021-02-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nextstep',
            constraint=models.UniqueConstraint(fields=('step', 'choice'), name='step_choice'),
        ),
    ]
