# Generated by Django 3.1.6 on 2021-02-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextstep',
            name='id',
        ),
        migrations.AlterField(
            model_name='nextstep',
            name='step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.step'),
        ),
    ]
