# Generated by Django 3.1.6 on 2021-02-16 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210215_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_step', to='api.step'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='additional_answer_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='NextStep',
        ),
    ]
