# Generated by Django 3.1.6 on 2021-02-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210216_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_interstitial',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='InterstitialStep',
        ),
    ]
