# Generated by Django 3.1.6 on 2021-02-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210216_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='step',
            name='is_go_to_meeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.step'),
        ),
        migrations.DeleteModel(
            name='FinalStep',
        ),
    ]
