# Generated by Django 3.1.6 on 2021-02-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210216_1838'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', False), ('is_go_to_meeting', False), ('is_interstitial', True)), fields=('is_interstitial', 'is_final', 'is_go_to_meeting'), name='interstitial_not_final'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(condition=models.Q(is_final=True), fields=('is_final', 'is_go_to_meeting'), name='go_to_meeting_if_final'),
        ),
    ]
