# Generated by Django 3.1.6 on 2021-02-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210216_1843'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='interstitial_not_final',
        ),
        migrations.RemoveConstraint(
            model_name='step',
            name='go_to_meeting_if_final',
        ),
    ]
