# Generated by Django 3.1.6 on 2021-02-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210217_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=1),
        ),
    ]
