# Generated by Django 3.1.6 on 2021-02-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210217_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalstep',
            old_name='is_go',
            new_name='should_go_to_meeting',
        ),
    ]
