# Generated by Django 3.1.6 on 2021-02-17 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210217_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_step', to='api.step'),
        ),
    ]
