# Generated by Django 3.1.6 on 2021-02-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210217_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(choices=[(0, 'No'), (1, 'Yes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.step'),
        ),
    ]
