# Generated by Django 3.1.6 on 2021-02-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210217_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
    ]
