# Generated by Django 3.1.6 on 2021-02-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210218_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='additional_answer_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Not Applicable')]),
        ),
    ]
