# Generated by Django 3.1.6 on 2021-02-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210218_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.step'),
        ),
    ]
