# Generated by Django 3.1.6 on 2021-03-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210306_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
    ]
