# Generated by Django 3.1.6 on 2021-03-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_step_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='children',
            field=models.ManyToManyField(related_name='_step_children_+', through='api.Choice', to='api.Step'),
        ),
    ]
